import gulp from 'gulp';
import babel from 'gulp-babel';
import print from 'gulp-print';
import nodemon from 'gulp-nodemon';
import path from 'path';

// contains the private config, of course do not commit it
import devConfig from './devConfig';

// build sources
gulp.task('build', () => (
  // #1. select all js files in the src folder
  gulp.src('src/**/*.js')
    // #2. print each file in the stream
    .pipe(print())
    // #3. transpile ES2015 to ES5 using ES2015 preset
    .pipe(babel())
    // #4. copy the results to the build folder
    .pipe(gulp.dest('dist'))
));

// start the server with restat in case of change using nodemon
gulp.task('dev', ['build'], () => {
  // assign the dev config to the environment process
  Object.assign(process.env, devConfig);
  nodemon({
    // the path of the file generated by the build
    script: path.join('dist', 'server.js'),
    ext: 'js',
    ignore: ['node_modules/**/*.js', 'dist/**/*.js'],
    // the task that should relaunch nodemon before restarting the server
    tasks: ['build'],
  });
});
